### ISSUE TITLE
Puppet 7 Support

### ISSUE THREAD

**Issue by QueerCodingGirl** [choria-io/general#19]
Does choria support / work with puppet 7?
Every documentation i could find mentions puppet 6, with the exception of the "Puppet 7 Support" of the choria/mcollective_agent_puppet version 2.4.1 module mentioned here: https://choria.io/blog/post/2021/03/29/april_releases/
and even for this module the forge.puppet.com still shows the "<= 6" constraint.

Slightly related to maybe-not-updated-docs: I saw a docker image on the docker hub, but can't find anything about a docker deployment in the docs under "Deployment". Is there a docker / docker-compose example running choria?

Maybe its only outdated and/or missing documentation, i can't tell.

**Comment by QueerCodingGirl** [comment]
Cool! Thank you for the fast response!
If theres Puppet 7 support then this site needs an update too: https://choria.io/docs/deployment/requirements/

If i would now go on and open an issue for a docker deployment option... are there any chances you would not close it with a "wont-do" label? ;)

**Comment by ripienaar** [comment]
If you want, there's a choria-io/website project where you can send a documentation update, else I can also.

Docker deployment for the central component - broker, etc - or for servers? I can see the value in the first of course but the problem is there's a bunch of implied dependencies.  For example, we need a CA, which CA would that docker deployment use? If you have Puppet, yeah I guess that can be used. So I guess the devil is in the details.

I am not against supporting more modern methods of course (see Helm, where we do solve the CA issue via cert-manager) but for the typical Puppet user I think it woldnt be widely used.

**Comment by QueerCodingGirl** [comment]
I think you are way faster than i am. The time it would take me to make the PR with the one line update to the docs vs. you doing the change...

I am currently running my complete puppet 7 stack inside docker. I am using the "pupperware" project from puppetlabs.
I would just need an example of the central components (broker etc.) with a minimal config in a docker-compose file format and then i could include that in my pupperware setup easily.

**Comment by ripienaar** [comment]
ok, well, the gross way is to run puppet inside docker to configure that instance of the broker, perhaps during a packer build of the base? That at least does not invalidate the documentation for you - since it would all just work.

Though thinking about it - as the container is aimed at the k8s work - it does not run the broker as root. Though of course also easy to show you a config of a puppet configured broker.

Start up https://github.com/choria-io/vagrant-demo and grab it from the puppet node

**Comment by ripienaar** [comment]
(updated docs, next build around next release will publish it)

**Comment by QueerCodingGirl** [comment]
Thank you for your support!
I will try the container made for k8s and look up a config example from the vagrant-demo. Might post a docker-compose example here when i got it running successfully here.

**Comment by ripienaar** [comment]
https://github.com/choria-io/puppet-choria/blob/main/templates/broker.cfg.epp is the puppet template that also sets up logging and such

**Comment by ripienaar** [comment]
fwiw

generate certificates for your broken by name lets say `choria.example.net` using puppetserver ca

Prepare a configuration directory as here ensuring files are owned by user 2048 - or readable 2048:

````
$ tree -u
.
├── [2048    ]  broker.conf
└── [2048    ]  ssl
    ├── [2048    ]  ca.pem
    ├── [2048    ]  cert.pem
    └── [2048    ]  key.pem

1 directory, 4 files
```

broker.conf has:

```
plugin.choria.broker_network = true
plugin.choria.network.listen_address = ::
plugin.choria.network.public_url = choria.example.net:4222

plugin.choria.ssldir = /etc/choria/ssl
plugin.security.provider = file
plugin.security.file.certificate = /etc/choria/ssl/cert.pem
plugin.security.file.key = /etc/choria/ssl/key.pem
plugin.security.file.ca = /etc/choria/ssl/ca.pem
plugin.security.file.cache = /etc/choria/ssl/cache
```

```
$ docker run -ti --rm -v `pwd`:/etc/choria -p 4222:4222 choria/choria:latest broker run --config /etc/choria/broker.conf
INFO[0000] Choria Broker version 0.20.2 starting with config /etc/choria/broker.conf
INFO[0000] Starting Network Broker
ERRO[0000] SRV lookup for _mcollective-broker._tcp failed: could not find your facter command
INFO[0000] Starting new Network Broker with NATS version 2.2.0-beta.58 on :::4222 using config file /etc/choria/broker.conf  component=network
INFO[0000] Starting nats-server                          component=network_broker
INFO[0000]   Version:  2.2.0-beta.58                     component=network_broker
INFO[0000]   Git:      [not set]                         component=network_broker
INFO[0000]   Name:     c0066e4753a9                      component=network_broker
INFO[0000]   ID:       NC3P6JOFANMMB4VKUGT7HREXQX53O2KENEKWXLBD53ROJ2XXPDWMZTV6  component=network_broker
INFO[0000] Listening for client connections on [::]:4222  component=network_broker
INFO[0000] TLS required for client connections           component=network_broker
INFO[0000] Server is ready                               component=network_broker
INFO[0000] Cluster name is CHORIA                        component=network_broker
INFO[0000] Listening for route connections on [::]:5222  component=network_broker
INFO[0000] Statistics gathering disabled, set plugin.choria.stats_port
```

At this point you're good to go, double check with nc from elsewhere

```
$ nc choria.example.net 4222
INFO {"server_id":"NCOFKSWHF3PZU6K4455KI5CWY5MMP4GCXGH7VLI5ARYORVDC3GOSQO3X","server_name":"a2006e9cd421","version":"2.2.0-beta.58","proto":1,"go":"go1.15.7","host":"choria.example.net","port":4222,"headers":true,"auth_required":true,"tls_required":true,"tls_verify":true,"max_payload":1048576,"client_id":2,"client_ip":"172.17.0.1","cluster":"CHORIA"}
```

make sure `host` is reported correctly

**Comment by QueerCodingGirl** [comment]
Why should this be set to file and not to puppet?

> plugin.security.provider = file

**Comment by QueerCodingGirl** [comment]
Thanks for the explanation! I have that part set up working with "puppet" (and without docker)

My current problem is that, despite getting good output on the "mco choria show_config" command, i do not get a response from the node(s) back when running "mco tasks run choria::ping -v --message teeeest" or when running "mco puppet status --dm=choria -v".
I only get this warning:
`warn 2021/10/08 16:39:49: client.rb:283:in `rescue in start_receiver' Could not receive all responses. Did not receive responses from local-hostname-where-puppet-and-choria-are-running.domain.tld
`

**Comment by ripienaar** [comment]
I'd have expected some server related logs there - I am guessing you set server.conf to debug and not broker.conf right? We want to see debug from the server.

Maybe also show ```choria inventory your.node --no-facts```

**Comment by QueerCodingGirl** [comment]
broker.conf is set to debug and to log into the file i posted here.

i believe i found the reason of my problem, but i have no idea where i could fix it.
when you look carefully at my posted command outputs you notice 2 different hostnames: puppet.domain.tld and cmp-puppet01.domain.tld
Thats not a censoring / copy-paste mistake from me. One is the hostname of that machine (cmp-puppet01...) and the other (puppet.domain.tld) is the FQDN i set up everything under. The FQDN also has its own ip address.

When i try to run "choria inventory puppet.domain.tld --no-facts" it works and when i use cmp-puppet01.domain.tld it fails with this message:

> FATA[0004] Could not run Choria: no inventory received

**Comment by ripienaar** [comment]
All right and if you try to run your task using -I fqdn of a working one then it works?

I am afk atm happy to just jump on a zoom next week and help you figure it out. Probably easiest. I am keen to get some docs/instruction up for that kind of deploy

**Comment by QueerCodingGirl** [comment]
Yes, the --dm=mc flag works too. I can't find "mc" in the docs, what is it for?


Would it be possible to get a config option in the choria server.conf like "ssl_alt_subjects_i_should_also_listen_to"? [1]
That would enable me to just configure the other FQDN as another thing this host would listen and respond to. It would not affect people that do not have this option set (backwards-compatible) and i only have to set it on hosts that have multiple FQDNs.

[1] ofc thats not the exact name i would give that option ;)

**Comment by ripienaar** [comment]
The `--dm=mc` is the default discovery method where it asks the fleet who is there and then access them by reported names, this avoids whatever confusion is between your puppetdb and your actual machines.

Regarding server/broker, please see, I think we have some terminology confusion https://choria.io/docs/concepts/architecture/

I think you mean the broker needing alt names well, it doesnt request its own cert - it just uses the cert already there, so its up to you to use Puppet methods for configuring the certnames and alt names and more.  But thats not the problem here.

The problem is your node has one FQDN and Choria is configured with another name, you need to pick one.

**Comment by QueerCodingGirl** [comment]
There is no confusion, i meant the choria-server. I have a server on the same node as the broker, because i want to manage this node as well as others.

I do not think that i need to pick one, because the infrastructure shouldn't conform to the tools, but the tools to the existing infrastructure. I have this setup with multiple names on one machine already present and for reasons that would go too far to explain here, that wont change any time soon. It would be great if i could still manage this node with choria, i just need a way to tell choria about this situation.

**Comment by QueerCodingGirl** [comment]
That setting is already set the whole time we were testing. I just tried leaving it out or setting it to the other name, it did not work. I can see the other name in the output but the node does not respond in any case while using --dm choria
Maybe the identity setting is not used/considered everywhere inside the code?

**Comment by ripienaar** [comment]
Choria is oppinionated about this, its probably not going to just let you change it like that because people  kept messing this up and relates to picking of the certificates by PuppetDB

``` 
Your certnames must match your FQDNs - the default
```

https://choria.io/docs/deployment/requirements/

So your only option - maybe - is to get `MCOLLECTIVE_CERTNAME=other.fqdn`

**Comment by ripienaar** [comment]
for me setting identity works - as in it tries to find a cert in puppet directory matching `identity`
